<a href="https://colab.research.google.com/github/Chaqmoqjon/Ma-lumotlarni-ishlash/blob/main/13_DateTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv("/content/database.csv") #yuqoridagi link orqali yuklandi
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [ ]:
import datetime as dt #date bilan ishlash uchun

In [ ]:
hozir = dt.datetime.now() #tekshirildi
print(hozir)

2025-01-25 14:53:54.761815

In [ ]:
hozir.hour, hozir.minute, hozir.second  #kabi har bir qismni alohida chiqarish mumkin

(14, 53, 54)

In [ ]:
df.info() #Date va Time object emas datetime turida bo'lishi kerak

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [ ]:
pd.to_datetime(df['Date'], format = "%m/%d/%Y") #ayrim kodlar formatga tushmadi
pd.to_datetime(df['Time'], format = "%H:%M:%S")

ValueError: time data "1975-02-23T02:58:41.000Z" doesn't match format "%m/%d/%Y", at position 2095. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
df['Date'].str.len().value_counts() #formatga tushmagan date lar soni. len() orqali topildi

Date
10    23409
24        3
Name: count, dtype: int64

In [ ]:
df['Time'].str.len().value_counts() #formatga tush,agan date lar soni. len() orqali topildi

Time
8     23409
24        3
Name: count, dtype: int64

In [ ]:
df[df['Date'].str.len() == 24] #formatga tushmaganlar ro'yxati

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
3378,1975-02-23T02:58:41.000Z,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,NaN,NaN,5.6,MB,...,NaN,NaN,NaN,NaN,NaN,USP0000A09,US,US,US,Reviewed
7512,1985-04-28T02:53:41.530Z,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.30,USP0002E81,US,US,HRV,Reviewed
20650,2011-03-13T02:23:34.520Z,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,NaN,32.3,NaN,NaN,1.06,USP000HWQP,US,US,GCMT,Reviewed

In [ ]:
df[df['Time'].str.len() == 24]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
3378,1975-02-23T02:58:41.000Z,1975-02-23T02:58:41.000Z,8.017,124.075,Earthquake,623.0,NaN,NaN,5.6,MB,...,NaN,NaN,NaN,NaN,NaN,USP0000A09,US,US,US,Reviewed
7512,1985-04-28T02:53:41.530Z,1985-04-28T02:53:41.530Z,-32.998,-71.766,Earthquake,33.0,NaN,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.30,USP0002E81,US,US,HRV,Reviewed
20650,2011-03-13T02:23:34.520Z,2011-03-13T02:23:34.520Z,36.344,142.344,Earthquake,10.1,13.9,289.0,5.8,MWC,...,NaN,32.3,NaN,NaN,1.06,USP000HWQP,US,US,GCMT,Reviewed

In [ ]:
df.loc[3378, 'Date'] = "02/23/1975" #har biri oy/kun/yil ga o'zgartirildi
df.loc[7512, 'Date'] = "04/28/1985"
df.loc[20650, 'Date'] = "03/13/2011"

In [ ]:
df.loc[3378, 'Time'] = "02:58:41" #har biri soat:daqiqa:soniya ga o'zgartirildi
df.loc[7512, 'Time'] = "02:53:41"
df.loc[20650, 'Time'] = "02:23:34"

In [ ]:
df['Date'].str.len().value_counts() #tekshirildi

Date
10    23412
Name: count, dtype: int64

In [ ]:
df['Time'].str.len().value_counts() #tekshirildi

Time
8    23412
Name: count, dtype: int64

In [ ]:
df['datetime'] = pd.to_datetime(df['Date'], format = "%m/%d/%Y") #qaytadan datetime ga o'tkazildi

In [ ]:
df['D_Time'] = pd.to_datetime(df['Time'], format = "%H:%M:%S").dt.time #qaytadan datetime ga o'tkazildi, agar soatni olmoqchi bo'lsang dt.time ni o'chir

In [ ]:
df.sample(10)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,D_Time
10686,12/02/1991,17:27:22,-15.867,-69.288,Earthquake,240.6,NaN,NaN,5.8,MW,...,NaN,NaN,0.90,USP0004ZYF,US,US,HRV,Reviewed,1991-12-02,17:27:22
2426,09/04/1972,13:42:19,35.941,73.387,Earthquake,30.0,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,ISCGEM769036,ISCGEM,ISCGEM,ISCGEM,Automatic,1972-09-04,13:42:19
724,08/13/1967,22:07:48,43.094,-0.731,Earthquake,10.0,NaN,NaN,5.7,MW,...,NaN,NaN,NaN,ISCGEM832236,ISCGEM,ISCGEM,ISCGEM,Automatic,1967-08-13,22:07:48
16098,12/23/2002,13:46:11,16.957,-85.578,Earthquake,33.0,NaN,288.0,6.0,MWB,...,NaN,NaN,0.91,USP000BM8T,US,US,US,Reviewed,2002-12-23,13:46:11
4607,12/13/1977,01:14:19,17.359,-54.848,Earthquake,33.0,NaN,NaN,6.4,MS,...,NaN,NaN,NaN,USP0000S1H,US,US,US,Reviewed,1977-12-13,01:14:19
2778,07/05/1973,00:58:45,43.988,147.849,Earthquake,40.0,NaN,NaN,5.5,MB,...,NaN,NaN,NaN,USP00002J6,US,US,US,Reviewed,1973-07-05,00:58:45
7133,08/07/1984,08:24:24,-15.406,166.868,Earthquake,33.0,NaN,NaN,5.5,MW,...,NaN,NaN,1.30,USP000268R,US,US,HRV,Reviewed,1984-08-07,08:24:24
3019,02/03/1974,16:12:57,-7.326,155.500,Earthquake,43.0,NaN,NaN,5.6,MS,...,NaN,NaN,NaN,USP000055K,US,US,US,Reviewed,1974-02-03,16:12:57
12843,01/04/1996,23:33:28,-55.574,-27.072,Earthquake,33.0,NaN,NaN,5.5,MS,...,NaN,NaN,1.10,USP0007ACF,US,US,US,Reviewed,1996-01-04,23:33:28
2112,10/03/1971,13:24:40,-14.571,171.680,Earthquake,10.0,NaN,NaN,6.7,MW,...,NaN,NaN,NaN,ISCGEM779005,ISCGEM,ISCGEM,ISCGEM,Automatic,1971-10-03,13:24:40

In [ ]:
df.at[0, 'datetime'].month # 0 qator, 'datetime' ustuni. Endi date sifatida ishlata olamiz

1

In [ ]:
df.at[0,'Time']

'13:44:18'

In [ ]:
df.at[0, 'D_Time'].hour

13

In [ ]:
df['month'] = df.datetime.dt.month
# df['hour'] = df['D_Time'].dt.hour

In [ ]:
df.sample(10)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,datetime,D_Time,month
9458,05/03/1989,15:41:31,30.053,99.499,Earthquake,7.5,NaN,NaN,5.8,MW,...,NaN,1.00,USP0003UUP,US,US,HRV,Reviewed,1989-05-03,15:41:31,5
9386,03/08/1989,02:34:26,-0.206,124.885,Earthquake,34.8,NaN,NaN,5.9,MW,...,NaN,1.10,USP0003SQR,US,US,NC,Reviewed,1989-03-08,02:34:26,3
12043,08/10/1994,14:57:49,-58.756,-25.538,Earthquake,33.0,NaN,NaN,5.5,MW,...,NaN,0.80,USP0006GSW,US,US,HRV,Reviewed,1994-08-10,14:57:49,8
17280,02/22/2005,02:25:23,30.754,56.816,Earthquake,14.0,NaN,652.0,6.4,MWC,...,NaN,1.31,USP000DGPX,US,US,HRV,Reviewed,2005-02-22,02:25:23,2
14146,10/10/1998,16:32:19,-0.403,119.840,Earthquake,33.0,NaN,NaN,6.0,MWC,...,NaN,1.24,USP0008WAK,US,US,HRV,Reviewed,1998-10-10,16:32:19,10
850,01/30/1968,03:44:25,-6.066,113.373,Earthquake,596.0,NaN,NaN,6.3,MW,...,NaN,NaN,ISCGEM827844,ISCGEM,ISCGEM,ISCGEM,Automatic,1968-01-30,03:44:25,1
18601,08/26/2007,12:37:31,-17.457,-174.335,Earthquake,127.4,NaN,567.0,6.1,MWC,...,NaN,0.97,USP000FKQX,US,US,GCMT,Reviewed,2007-08-26,12:37:31,8
2648,03/16/1973,03:40:42,2.058,126.396,Earthquake,33.0,NaN,NaN,5.6,MB,...,NaN,NaN,USP00000YX,US,US,US,Reviewed,1973-03-16,03:40:42,3
19040,06/10/2008,04:13:38,-18.098,167.880,Earthquake,35.0,NaN,169.0,5.9,MWC,...,NaN,1.17,USP000G933,US,US,GCMT,Reviewed,2008-06-10,04:13:38,6
11190,11/05/1992,19:53:23,-5.263,152.575,Earthquake,19.8,NaN,NaN,6.2,MW,...,NaN,1.20,USP0005GBW,US,US,HRV,Reviewed,1992-11-05,19:53:23,11

In [ ]:
df.month.value_counts() #xulosa: mart oyida eng ko'p zizilalar bo'lgan, iyun oyida eng kami bo'lgan

month
3     2114
8     2014
12    2001
11    1987
9     1985
4     1971
5     1964
10    1952
1     1891
7     1880
2     1829
6     1824
Name: count, dtype: int64

In [ ]:
#  df.hour.value_counts() #xulosa: soat 13 larda eng ko'p zizilalar bo'lgan, soat 16 larda eng kami bo'lgan