<a href="https://colab.research.google.com/github/Chaqmoqjon/Ma-lumotlarni-ishlash/blob/main/16_concat_%26_pivot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
bank = pd.read_csv('https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/bank.csv', sep=';')
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [ ]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [ ]:
bank1, bank2 = bank[:2520], bank[2521:]
bank2

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
2521,46,unemployed,married,secondary,no,3533,yes,no,cellular,12,aug,235,2,-1,0,unknown,no
2522,59,blue-collar,divorced,secondary,no,3573,no,no,cellular,15,may,44,1,-1,0,unknown,no
2523,44,management,divorced,tertiary,no,476,yes,yes,unknown,26,may,127,2,-1,0,unknown,no
2524,35,blue-collar,married,secondary,no,1257,yes,no,cellular,20,apr,93,3,329,7,failure,no
2525,55,blue-collar,married,unknown,no,23,no,no,cellular,30,jan,143,1,2,3,other,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [ ]:
pd.concat([bank1, bank2]) #kamida 2 ta dataset ulanadi. pastga tushdi

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/refs/heads/master/data_pivot.csv', sep=',')
data

                              date     item      value
0    1959-03-31 23:59:59.999999999  realgdp   2710.349
1    1959-03-31 23:59:59.999999999     infl      0.000
2    1959-03-31 23:59:59.999999999    unemp      5.800
3    1959-06-30 23:59:59.999999999  realgdp   2778.801
4    1959-06-30 23:59:59.999999999     infl      2.340
..                             ...      ...        ...
604  2009-06-30 23:59:59.999999999     infl      3.370
605  2009-06-30 23:59:59.999999999    unemp      9.200
606  2009-09-30 23:59:59.999999999  realgdp  12990.341
607  2009-09-30 23:59:59.999999999     infl      3.560
608  2009-09-30 23:59:59.999999999    unemp      9.600

[609 rows x 3 columns]

In [ ]:
pivoted_data = data.pivot(index='date', columns='item', values='value')
pivoted_data

item                           infl    realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

In [ ]:
data['value2'] = np.random.randn(len(data))
data

                              date     item      value    value2
0    1959-03-31 23:59:59.999999999  realgdp   2710.349  0.751403
1    1959-03-31 23:59:59.999999999     infl      0.000  0.709639
2    1959-03-31 23:59:59.999999999    unemp      5.800 -1.111673
3    1959-06-30 23:59:59.999999999  realgdp   2778.801  0.367093
4    1959-06-30 23:59:59.999999999     infl      2.340  0.936427
..                             ...      ...        ...       ...
604  2009-06-30 23:59:59.999999999     infl      3.370 -0.108568
605  2009-06-30 23:59:59.999999999    unemp      9.200 -0.145751
606  2009-09-30 23:59:59.999999999  realgdp  12990.341  0.604100
607  2009-09-30 23:59:59.999999999     infl      3.560 -1.544835
608  2009-09-30 23:59:59.999999999    unemp      9.600 -0.513102

[609 rows x 4 columns]

In [ ]:
pivoted_data2 = data.pivot(index='date', columns='item', values= ['value', 'value2'])
pivoted_data2

                              value                     value2            \
item                           infl    realgdp unemp      infl   realgdp
date
1959-03-31 23:59:59.999999999  0.00   2710.349   5.8  0.709639  0.751403
1959-06-30 23:59:59.999999999  2.34   2778.801   5.1  0.936427  0.367093
1959-09-30 23:59:59.999999999  2.74   2775.488   5.3  0.717802 -0.316410
1959-12-31 23:59:59.999999999  0.27   2785.204   5.6  0.556833  0.795344
1960-03-31 23:59:59.999999999  2.31   2847.699   5.2  0.628465 -0.211752
...                             ...        ...   ...       ...       ...
2008-09-30 23:59:59.999999999 -3.16  13324.600   6.0  0.188596 -0.277924
2008-12-31 23:59:59.999999999 -8.79  13141.920   6.9 -0.083340 -0.620761
2009-03-31 23:59:59.999999999  0.94  12925.410   8.1  0.365513 -0.239507
2009-06-30 23:59:59.999999999  3.37  12901.504   9.2 -0.108568 -2.202165
2009-09-30 23:59:59.999999999  3.56  12990.341   9.6 -1.544835  0.604100


item                              unemp
date
1959-03-31 23:59:59.999999999 -1.111673
1959-06-30 23:59:59.999999999 -0.231971
1959-09-30 23:59:59.999999999 -1.369772
1959-12-31 23:59:59.999999999 -1.423217
1960-03-31 23:59:59.999999999 -0.012691
...                                 ...
2008-09-30 23:59:59.999999999  2.340968
2008-12-31 23:59:59.999999999 -0.295942
2009-03-31 23:59:59.999999999 -0.119034
2009-06-30 23:59:59.999999999 -0.145751
2009-09-30 23:59:59.999999999 -0.513102

[203 rows x 6 columns]