<a href="https://colab.research.google.com/github/Chaqmoqjon/Ma-lumotlarni-ishlash/blob/main/8_dropna_fillna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv

--2025-01-24 03:23:18--  https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2913 (2.8K) [text/plain]
Saving to: ‘automobile_data_nan.csv’

automobile_data_nan 100%[===================>]   2.84K  --.-KB/s    in 0s

2025-01-24 03:23:19 (37.1 MB/s) - ‘automobile_data_nan.csv’ saved [2913/2913]

In [ ]:
df = pd.read_csv('automobile_data_nan.csv', index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [ ]:
df.isnull().sum() / len(df) * 100 # har bir qatorning necha foiz (%) ma'lumoti NaN qiymatda ekanligini aytadi

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

##NaN larni o'chirish

In [ ]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [ ]:
len(df.dropna()) #NaN qiymat tashlab yuborilgandan keyingi qiymati

14

In [ ]:
df.dropna(axis = 1) #ustun bo'yicha o'chirish

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [ ]:
df.dropna(axis = 1, thresh=48) #agar ustunda 48 ta ma'lumot bo'lsa ustun qoladi aks holda o'chadi

           company   body-style  length engine-type num-of-cylinders    price
index
0      alfa-romero  convertible   168.8        dohc             four  13495.0
1      alfa-romero  convertible   168.8        dohc             four  16500.0
2      alfa-romero    hatchback   171.2        ohcv              six  16500.0
3             audi        sedan   176.6         ohc             four  13950.0
4             audi        sedan   176.6         ohc             five  17450.0
...            ...          ...     ...         ...              ...      ...
81      volkswagen        sedan   171.7         ohc             four   7975.0
82      volkswagen        sedan   171.7         NaN             four   7995.0
86      volkswagen        sedan     NaN         ohc             four   9995.0
87           volvo        sedan   188.8         NaN             four  12940.0
88           volvo        wagon   188.8         ohc             four  13415.0

[61 rows x 6 columns]

In [ ]:
df2 = df.dropna(subset=['price', 'horsepower']) # faqat biz bergan ustunni NaN ga tekshirib o'chiradi, inplace = True joyida saqlash
df2.shape

(43, 9)

##NaN larni to'ldirish

In [ ]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [ ]:
df.fillna(0) # NaN qiymatlar o'rniga 0 qo'yildi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

In [ ]:
df.fillna({'horsepower' : round(np.mean(df['horsepower']), 2), 'wheel-base' : 95 }) # berilgan ustunlarni to'ldirish

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,108.27,21.0,13495.0
1,alfa-romero,convertible,95.0,168.8,dohc,four,111.00,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.00,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.00,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,108.27,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.00,27.0,7975.0
82,volkswagen,sedan,95.0,171.7,NaN,four,52.00,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.00,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.00,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,108.27,23.0,13415.0

In [ ]:
df.fillna(method = 'ffill') # forward fill, o'zidan yuqoridagindan qiymatni olib to'ldiradi

<ipython-input-25-633802c18652>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill') # forward fill, o'zidan yuqoridagindan qiymatni olib to'ldiradi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [ ]:
df.fillna(method = 'bfill') # back fill, o'zidan orqadagindan qiymatni olib to'ldiradi

<ipython-input-26-b50bccd2f303>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill') # back fill, o'zidan orqadagindan qiymatni olib to'ldiradi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df[df.company == 'toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df[df.company == 'toyota'] = df[df.company == 'toyota'].fillna(method = 'bfill') # toyota ning NaN qiymatlari to'dirildi

<ipython-input-33-d6c86bfb47cb>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company == 'toyota'] = df[df.company == 'toyota'].fillna(method = 'bfill') # toyota ning NaN qiymatlari to'dirildi

In [ ]:
df[df.company == 'toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df.fillna(round(df.mean(numeric_only=True), 2)) #barcha ustunlar uchun o'rtachani joylash

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.60,168.80,dohc,four,108.3,21.0,13495.0
1,alfa-romero,convertible,99.07,168.80,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.50,171.20,ohcv,six,154.0,25.7,16500.0
3,audi,sedan,99.80,176.60,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.40,176.60,ohc,five,108.3,25.7,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.30,171.70,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,99.07,171.70,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.30,173.77,ohc,four,100.0,25.7,9995.0
87,volvo,sedan,104.30,188.80,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.30,188.80,ohc,four,108.3,23.0,13415.0

In [ ]:
dfh = df[df['body-style'] == 'hatchback']
dfh.fillna(dfh.mean(numeric_only=True)) #body-style bo'yicha to'ldirish

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.5,171.200,ohcv,six,154.000000,32.727273,16500.000000
16,chevrolet,hatchback,88.4,141.100,l,three,77.363636,47.000000,5151.000000
17,chevrolet,hatchback,94.5,155.900,ohc,four,70.000000,38.000000,6295.000000
19,dodge,hatchback,93.7,157.300,ohc,four,68.000000,31.000000,6377.000000
20,dodge,hatchback,93.7,159.325,ohc,four,68.000000,32.727273,6229.000000
36,mazda,hatchback,93.1,159.100,NaN,four,77.363636,32.727273,5195.000000
37,mazda,hatchback,93.1,159.100,ohc,four,68.000000,31.000000,6095.000000
38,mazda,hatchback,93.1,159.100,ohc,four,68.000000,31.000000,6795.000000
39,mazda,hatchback,94.1,159.325,NaN,two,101.000000,17.000000,11845.000000
49,mitsubishi,hatchback,94.1,157.300,ohc,four,77.363636,37.000000,5389.000000
50,mitsubishi,hatchback,93.7,159.325,NaN,four,68.000000,31.000000,6189.000000
63,porsche,hatchback,98.4,175.700,dohcv,eight,77.363636,32.727273,7159.571429
66,toyota,hatchback,95.7,158.700,ohc,four,62.000000,35.000000,5348.000000
67,toyota,hatchback,95.7,158.700,ohc,four,62.000000,31.000000,6338.000000
68,toyota,hatchback,95.7,158.700,ohc,four,62.000000,31.000000,6488.000000